### ISSUE TITLE
Variable to control conflicts between files with same base name

### ISSUE THREAD

**Issue by aksharvarma** [007kevin/pdf-view-restore#2]
> Do note pdf documents with the same name will conflict with this setting, but you get the ability to move pdf documents around and still keeping the save information in sync.

Is there a reason this setting is not done as a customizable variable? While I can see the appeal for the current setting, I would prefer that the full path is used to determine files. This conflict kind of messed with my auctex+synctex config and it took me a while to debug this package as the source.

And if I'm not mistaken adding a variable should be as simple using something like this
```
(if use-file-base-name-flag
    (file-name-base buffer-file-name)
  buffer-file-name)
```
instead of simply having: `(file-name-base buffer-file-name)` in the `pdf-view-restore-key` function.

Would you be open to a pull request with this change?

**Comment by 007kevin** [comment]
I think that change is reasonable. If you submit a pull request, I'll be happy to review and merge.
