### ISSUE TITLE
pdf-view-restore does not restore when Emacs startup with desktop.el's `desktop-save-mode`

### ISSUE THREAD

**Issue by stardiviner** [007kevin/pdf-view-restore#5]
I use Emacs desktop.el's `desktop-save-mode` for saving session. But when I restart Emacs, I found opened PDF files are not restored position. They are at the PDF file beginning position.

**Comment by stardiviner** [comment]
After some dive into source code. Seems `pdf-view-restore` is hooked on `pdf-view-after-change-page-hook`. But It does not hook on `find-file` hook which is used by `desktop-save-mode` to open session files. I think `pdf-view-restore` need to be improved.

**Comment by stardiviner** [comment]
I tried this hook configuration, but still does not work.
```elisp
(use-package pdf-view-restore
  :ensure t
  :demand t
  :commands (pdf-view-restore)
  ;; FIXME hook on `find-file-hook' to fix `desktop-save-mode' restore session invalid issue.
  :hook ((file-file . pdf-view-restor)
         (pdf-view-mode . pdf-view-restore-mode)))
```

**Comment by 007kevin** [comment]
Can you share how you're restoring the desktop session? 

I tried the following and found restoring desktop reopens pdf correctly:
1. Open pdf
2. `desktop-save`
3. close and reopen Emacs
4. `desktop-read`
5. Pdf buffer reopens to the correct page.

**Comment by stardiviner** [comment]
@007kevin Thanks for reviewing.
Here is my `desktop-save-mode` config:
```elisp
(use-package desktop
  :if (not (or (featurep 'esup)
               my/emacs-benchmark-toggle))
  :ensure t
  :config
  (setq desktop-files-not-to-save "\\(^/[^/:]*:\\|(ftp)$\\|^/tmp/\\)")
  (let ((desktop-dir (concat user-emacs-directory ".desktop-save")))
    (unless (file-exists-p desktop-dir)
      (make-directory desktop-dir))
    (add-to-list 'desktop-path desktop-dir))
  (setq desktop-auto-save-timeout (* 60 10))
  (add-hook 'after-init-hook #'desktop-save-mode))
```

**Comment by stardiviner** [comment]
I confirmed it does not work on my minimal Emacs config.
I adjusted my desktop.el config a little.
```elisp
(load (expand-file-name "init/init-package.el" user-emacs-directory))
(require 'init-package) ; this just a init file about `package.el` configs nothing specific others.

(use-package pdf-tools
  :ensure t
  :preface (pdf-loader-install)
  :mode  ("\\.pdf\\'" . pdf-view-mode)
  :magic ("%PDF" . pdf-view-mode))

(use-package pdf-view-restore
  :ensure t
  :demand t
  :commands (pdf-view-restore)
  ;; FIXME hook on `find-file-hook' to fix `desktop-save-mode' restore session invalid issue.
  :hook ((pdf-view-mode . pdf-view-restore-mode)
         ;; (file-file . pdf-view-restore)
         ))

(use-package desktop
  :ensure nil
  :config
  (let ((my/desktop-dir (concat user-emacs-directory ".desktop-save")))
    (unless (file-exists-p my/desktop-dir)
      (make-directory my/desktop-dir))
    (add-to-list 'desktop-path my/desktop-dir)
    (setq desktop-dirname my/desktop-dir))
  (desktop-revert)
  (desktop-save-mode 1)
  (setq desktop-files-not-to-save "\\(^/[^/:]*:\\|(ftp)$\\|^/tmp/\\)")
  (setq desktop-auto-save-timeout (* 60 10)))
```
The steps to reproduce:
1. emacs -q -l minimal.el # the minimal.el contains upper config
2. then open an org file, open an PDF file, scroll down to a specific page.
3. execute command `desktop-save-in-desktop-dir`
4. close emacs
5 . start emacs to see whether it restore PDF document position.

**Comment by stardiviner** [comment]
Gentle ping ....
